### ISSUE TITLE
Infinite loop when using Matcher.namedGroups

### ISSUE THREAD

**Issue by vprcic** [tony19/named-regexp#19] opened 2022-09-06 09:51 UTC
It seems that if the pattern matches an empty string, an infinite loop occurs when using Matcher.namedGroups, even if the matched input isn't an empty string. Here's a code example:

```
Pattern pattern = Pattern.compile("(?<first>A)?(?<second>B)?");
Matcher matcher = pattern.matcher("AB");
if(matcher.matches()) {
    matcher.namedGroups();
}
```

**Comment by tony19** [comment] 2022-09-07 04:43
Duplicate of #16. Fixed in #17. Not yet released.

**Closed by tony19** 2022-09-07 04:43 UTC

**Comment by tony19** [comment] 2022-09-08 01:32
Fixed in https://github.com/tony19/named-regexp/releases/tag/named-regexp-0.2.7
